### PR TITLE
gulp script updations, static files serving

### PR DESCRIPTION
**Pull request by rashivkp**
I have done filtering, unwanted folders removed.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/LibreCoopIn/OpenAuto-Server/pull/3" target="_blank">ReviewNinja

**Comment by joicemjoseph** [comment]
@rashivkp what about @houndci-bot suggestions ?

**Review by joicemjoseph — CHANGES_REQUESTED** [review]
shall we follow some standards, like what @houndci-bot suggested ?

**Comment by rashivkp** [comment]
I think, now its ready to go. you can ignore the suggestion in the config.rb file

**Pull request merged**
